---
- name: Remove any existing docker-storage config file
  file:
    path: "/etc/sysconfig/docker-storage"
    state: absent

- name: Create the docker-storage config file
  template:
    src: "{{ role_path }}/templates/docker-storage-setup.j2"
    dest: "/etc/sysconfig/docker-storage-setup"
    owner: root
    group: root
    mode: 0644
