---
vmware:
  host: foo-host
  username: foo-user
  password: foo-password

  datacenter: FOO-DATACENTER-NAME
  cluster: FOO-CLUSTER-NAME
  resource_pool: foo_resource_pool
  folder: foo_folder
  datastore: foo-datastore-name

  vm_network: "VM Network"
  vm_templates:
  - vm-template-copy1
  - vm-template-copy2
  - vm-template-copy3

  vm_parameters:
    masters:
      names:
      - ocp311-ga-master-0
      num_cpus: 1
      ram_mb: 16384
      system_disks_gb: [60, 40, 40]
      system_disks_type: thin
    nodes:
      names:
      - ocp311-ga-compute-1
      - ocp311-ga-compute-2
      num_cpus: 2
      ram_mb: 32768
      system_disks_gb: [60, 40, 40]
      system_disks_type: thin
    glusterfs:
      names:
      - ocp311-ga-storage-1
      - ocp311-ga-storage-2
      - ocp311-ga-storage-3
      num_cpus: 1
      ram_mb: 16384
      system_disks_gb: [60, 40, 40]
      system_disks_type: thin
      storage_disks_gb: [10, 20, 10]
      storage_disks_type: thin
    glusterfs_registry:
      names:
      - ocp311-ga-storage-registry-1
      - ocp311-ga-storage-registry-2
      - ocp311-ga-storage-registry-3
      num_cpus: 1
      ram_mb: 16384
      system_disks_gb: [60, 40, 40]
      system_disks_type: thin
      storage_disks_gb: [10, 20, 10]
      storage_disks_type: thin
vm:
  repo:
    upstream:
      skip: no
      subscription_server: subscription.foo.bar
      subscription_baseurl: http://cdn.redhat.com/
      subscription_user: foo@bar.quuz
      subscription_pass: FooPassword
      subscription_pool: FooUser
      repositories_to_enable:
        all:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-fast-datapath-rpms
        - rhel-7-server-ose-3.11-rpms
        masters:
        - rh-gluster-3-for-rhel-7-server-rpms
        nodes: []
        glusterfs:
        glusterfs_registry:
    downstream:
      skip: yes
      repositories_to_enable:
        all:
        - name: 'downstream-fake-repo-common-for-all-nodes'
          url: 'http://quuz.zuuq/x86_64/os/'
          cost: 1000
        masters: []
        nodes:
        - name: 'downstream-fake-repo-for-compute-nodes'
          url: 'http://quuz.zuuq/x86_64/os/'
          cost: 990
        glusterfs:
        - name: 'downstream-fake-repo-for-glusterfs-nodes-1'
          url: 'http://foo.oof/x86_64/os/'
          cost: 990
        glusterfs_registry:
  yum:
    update: yes
    reboot_after_update: yes
    sleep_after_reboot_sec: 30
  uninstall_packages:
    all:
    - fake-package-1
    - fake-package-2
    masters:
    nodes: []
    glusterfs: []
    glusterfs_registry: []
  install_packages:
    all:
    - "docker==1.12.6"
    - sos
    masters:
    nodes: []
    glusterfs: []
    glusterfs_registry: []
  setup_and_configuration:
    setup_common_packages: yes
    setup_ntp: yes
    setup_vmware_tools: yes
    mount_disks:
    - disk_path: "/dev/sdb"
      mount_point: "/var"
      name_prefix: "var"
      fstype: "xfs"
    setup_docker_storage:
      skip: no
      disk_path: "/dev/sdc"
    setup_standalone_glusterfs: no
    setup_standalone_glusterfs_registry: no
ocp_update:
  heketi:
    install_client_on_masters: yes
    client_package_url: 'http://foo.bar/x86_64/os/Packages/heketi-client-8.0.0-10.el7rhgs.x86_64.rpm'
    add_public_ip_address: yes
cluster_validation:
  skip: yes
  heketi_pod:
    redhat_storage_release: "Red Hat Gluster Volume Manager 3.11.3"
    redhat_release: "Red Hat Enterprise Linux Server release 7.6"
    packages:
    - heketi-8.0.0-12
    - heketi-client-8.0.0-12
    validate_package_signatures: yes
  gluster_pod:
    redhat_storage_release: "3.4.4"
    redhat_release: "Red Hat Enterprise Linux Server release 7.6"
    packages:
    - glusterfs-3.12.2-47
    - gluster-block-0.2.1-32
    - tcmu-runner-1.2.0-29
    - lvm2-2.02.180-10
    validate_package_signatures: yes
  gluster_block_provisioner_pod:
    redhat_storage_release: "Red Hat Gluster Block Provisioner 3.11.3"
    redhat_release: "Red Hat Enterprise Linux Server release 7.6"
    packages:
    validate_package_signatures: yes
tests_config_updates:
  common.allow_heketi_zones_update: False
  common.stop_on_first_failure: False
common:
  output_tests_config_file: ../tests_config.yaml
  output_cluster_info_file: ../cluster_info.yaml
