# Expected vars:
#
# - 'config_filepath' - required. It is expected to be provided and must
# store filepath for the config file.
#
# Command to run only this playbook:
#
# $ tox -e ocp3.11 -- ansible-playbook -i inventory-file.yaml \
#     control_playbook.yaml \
#     -e config_filepath=/path/to/the/config.yaml \
#     -e ocp_playbooks=playbooks/prerequisites.yml,playbooks/deploy_cluster.yml \
#     --tags all
---
# Step 1: Provision nodes which will be used for OpenShift deployment
- import_playbook: 1_provision_nodes.yaml
  tags: ['1', 'node_provision', 'node_provisioning']

# Step 2: Configure provisioned nodes
- import_playbook: 2_configure_nodes.yaml
  tags: ['2', 'node_configure']

# Step 3: Run OpenShift deployment using specified inventory file and playbooks
- import_playbook: 3_ocp_deployment.yaml
  tags: ['3', 'ocp_deploy', 'ocp_deployment']

# Step 4: Run additional actions after OpenShift deployment
- import_playbook: 4_ocp_update.yaml
  tags: ['4', 'ocp_update']

# Step 5: Generate config file for tests
- import_playbook: 5_generate_tests_config.yaml
  tags: ['5', 'tests_config']

# Step 6: Provide info about deployed OpenShift cluster
- import_playbook: 6_gather_cluster_info.yaml
  tags: ['6', 'cluster_info']
